title: Karma Mustafa
description: Paintings & Sculptures
baseurl: "https://karma.mustafa.github.io"
url: ""

collections:
  artworks:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: artworks
    values:
      layout: artwork
