title: Karma Mustafa
description: Paintings & Sculptures
url: "https://oxoh.github.io"
baseurl: "/karma.mustafa.github.io"  # <-- important for project page


collections:
  artworks:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: artworks
    values:
      layout: artwork
