title: Karma Mustafa
description: Paintings & Sculptures
url: ""
baseurl: ""  # <-- important for project page


collections:
  artworks:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: artworks
    values:
      layout: artwork
